# Generated by Django 5.1.2 on 2024-12-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
